language: node_js
node_js:
- 6.9.2
env:
  global:
  - GH_REF=github.com/zarlex/frontend
  - secure: AxfFCMSkaEu0Dz6Gc6y8wyOKsyCGgIDp8WsWrunDgFUhC9jplAlkiTkLaHr7aP8ZwmhXgyQ+lHodkUs0vBlPqM+Ow074S2SeljAdZfbiwkbSbh2s3Prmw4RN+GZaYtyqWZCPLj5xqPG4Cl4USvGTGVSzby9quXgaQZ8SPX2Hvi6Folc3s28IivRobNS1BXx84WU0IAgLfneYJTf23csIGoFoAMqSTyY4/tma1yhJXkoASX0QH9HeHq+SXM37qoclCbG9tm8PaY/7ivxlk6bFYC2WSbp6BqlYOWxEF6yBheZxiDT12vcte/85Uj4qun41anAjIpqNjrUMK8ijBm5ubT03iIyVHFl/7ipfQFx/EFVkQf/6CM2IkaU8h5vms615vir2/NFnbZxiByEQabcegmTI2+iDYq5QrBNWz4oTQOEMg5cYkzQtzfPdQGlVdkhaGiTiDLCGQoMHUZva8fzRsNLN3JCmafMHPxEOd+FU2uUI7kKMledWp0L8fczwUA7v49T2zkC9Oqk4fajXJxcU2rqaDTcbtUy1k/5tQJkisdeg8HSRspeZM20e8GwufG1OW7R/YVWXcP1e7h7WTo/ivSO9PsHzRh8TMTyvNtaHjFmmXZjYt7pZmXw3Knn09ovqEJlpbYOIHPJuBDIrNhcH9uIqgtb7ulOouwHx5kCjHDg=
before_install:
- npm install -g webpack
before_deploy:
- npm run build
deploy:
- provider: script
  script: ./bin/github_pages_release.sh
  skip_cleanup: true
  on:
    branch: master
